services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/${localWorkspaceFolderBasename:-codexsun}:cached
    command: sleep infinity
    networks:
      - codexion-network
    environment:
      Database__Master__ConnectionString: server=mariadb;port=3306;database=codexsun_dev;user=root;password=Computer.1;
      Database__Tenant__ConnectionStringTemplate: server=mariadb;port=3306;database={database};user=root;password=Computer.1;

networks:
  codexion-network:
    name: codexion-network
    external: true
